version: "3.8"
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: boD98Ot3Dv6
      POSTGRES_DB: noti
    networks:
      - noti
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: boD98Ot3Dv6
      POSTGRES_DB: noti
    networks:
      - noti
networks:
  noti:
